### ISSUE TITLE
Getting Error with lastest download

### ISSUE THREAD

**Issue by wasimjee** [mgp25/Chat-API-NET#52]
Error	1
Delegate 'OnGetMessageReceivedDelegate' does not take 2 arguments
Base\WhatsEventBase.cs
Line No : 153

Error	2
No overload for method 'fireOnGetMessageReceivedClient' takes 2 arguments
Base\WhatsSendBase.cs
Line No : 213

Error	3
No overload for method 'MakeId' takes 1 arguments
WhatsApp.cs
Line No : 723

Error	4
No overload for method 'MakeId' takes 1 arguments
WhatsApp.cs
Line No : 740

even 
Unable to cast object of type 'WhereSelectArrayIterator`2[System.String,WhatsAppApi.Helper.ProtocolTreeNode]' to type 'WhatsAppApi.Helper.ProtocolTreeNode'.

while creating group 

code : 
String[] numbers = {"97xxxxxxxxxx","97xxxxxxxxxx"};
                
wa.SendCreateGroupChat("HelloGG",numbers);

**Comment by WHAnonymous** [comment]
Fixed

**Comment by wasimjee** [comment]
Still getting this error on creating group

Unable to cast object of type 'WhereSelectListIterator`2[System.String,WhatsAppApi.Helper.ProtocolTreeNode]' to type 'WhatsAppApi.Helper.ProtocolTreeNode'.
